channels:
  - conda-forge
  - defaults
  - pytorch
  - anaconda
  - pyviz
  - numba
dependencies:
  - python=3.7
  - bayesian-optimization
  - bokeh
  - catboost
  - cudatoolkit=9.0
  - holoviews
  - hyperopt
  - jupyter
  - jupyterlab
  - lightgbm
  - matplotlib
  - nodejs
  - numba
  - numpy
  - pandas
  - pytest
  - pytorch
  - requests
  - scikit-image
  - scikit-learn
  - scikit-optimize
  - scipy
  - seaborn
  - torchvision
  - tqdm
  - xgboost
  - xlrd
  - pip:
      - albumentations
      - catalyst
      - watermark
